Repository STACK-UP-3/champs-backend, pull requests merged in 2020-04, with the labels that each got.

#11 171648170-story(signup): create signup feature
  .eslintrc
  .travis.yml
  package-lock.json
  package.json
  server/config/winston.js
  server/controllers/authController.js
  server/helpers/authHelpers.js
  server/index.js
  server/middlewares/checkUser.js
  server/middlewares/validateAuth.js
  server/routes/auth.js
  server/routes/index.js
  server/schemas/authSchema.js
  server/sequelize/migrations/20200325105904-create-user.js
  server/sequelize/models/user.js
  server/sequelize/seeders/20200325133338-User.js
  server/tests/auth.test.js
  swagger.json
Labels: TTL Review

#12 171648169 Feature of signing in a user
  .env.example
  .eslintrc
  .travis.yml
  package-lock.json
  package.json
  server/config/fixtures.json
  server/config/passport.js
  server/config/winston.js
  server/controllers/authController.js
  server/helpers/authHelpers.js
  server/helpers/passwordHandler.js
  server/helpers/tokenHelper.js
  server/helpers/verifyUser.js
  server/index.js
  server/middlewares/checkUser.js
  server/middlewares/validateAuth.js
  server/routes/auth.js
  server/schemas/authSchema.js
  server/sequelize/seeders/20200325133338-User.js
  server/tests/auth-signin.test.js
  swagger.json
Labels: TTL Review

#13 171648174 Add reset password
  .hound.yml
  package-lock.json
  package.json
  server/config/winston.js
  server/controllers/authController.js
  server/controllers/resetController.js
  server/helpers/authHelpers.js
  server/index.js
  server/middlewares/validateAuth.js
  server/routes/auth.js
  server/routes/index.js
  server/schemas/authSchema.js
  server/sequelize/models/user.js
  server/sequelize/seeders/20200325133338-User.js
  server/tests/auth.test.js
  server/tests/passwordResetTest.test.js
  swagger.json
Labels: TTL Review

#16 171648176-update-user: create update user data feature
  server/controllers/authController.js
  server/controllers/userController.js
  server/helpers/UserHelper.js
  server/helpers/authHelpers.js
  server/middlewares/checkUser.js
  server/middlewares/validateUser.js
  server/routes/index.js
  server/routes/user.js
  server/schemas/userSchema.js
  server/sequelize/migrations/20200325105904-create-user.js
  server/sequelize/models/user.js
  server/sequelize/seeders/20200325133338-User.js
  server/tests/app.test.js
  server/tests/auth.test.js
  server/tests/user.test.js
Labels: Peer Review

#21 172264488 Fix the Hound issues and increase the Coverage
  .env.example
  server/controllers/resetController.js
  server/tests/passwordResetTest.test.js
Labels: Peer Review, TTL Review

#22 #171648182 add user role settings endpoint
  .eslintrc
  .gitignore
  .sequelizerc
  .travis.yml
  package.json
  server/controllers/UserController.js
  server/controllers/authController.js
  server/helpers/UserHelper.js
  server/helpers/asyncErrorHandler.js
  server/helpers/authHelpers.js
  server/helpers/log.util.js
  server/helpers/paginationHelper.js
  server/helpers/passwordHashHelper.js
  server/helpers/tokenHelper.js
  server/helpers/verifyUser.js
  server/index.js
  server/middlewares/isSuperAdmin.js
  server/middlewares/paginationMiddleware.js
  server/middlewares/paginationValidator.js
  server/middlewares/roleValidator.js
  server/middlewares/tokenValidator.js
  server/routes/index.js
  server/routes/userRoute.js
  server/sequelize/migrations/20200325105904-create-user.js
  server/sequelize/models/user.js
  server/sequelize/seeders/20200325133338-User.js
  server/tests/app.test.js
  server/tests/mochData/users.js
  server/tests/roleSetting.test.js
  server/tests/users.test.js
  swagger.json
Labels: TTL Review

#20 171648176-update-user: create update user data feature
  package.json
  server/controllers/UserController.js
  server/controllers/authController.js
  server/helpers/UserHelper.js
  server/helpers/authHelpers.js
  server/helpers/verifyUser.js
  server/middlewares/checkUser.js
  server/middlewares/profileOwner.js
  server/middlewares/validateUser.js
  server/routes/index.js
  server/routes/user.js
  server/schemas/authSchema.js
  server/schemas/userSchema.js
  server/sequelize/migrations/20200325105904-create-user.js
  server/sequelize/models/user.js
  server/sequelize/seeders/20200325133338-User.js
  server/tests/auth.test.js
  server/tests/user.test.js
  swagger.json
Labels: TTL Review

#15 #171648173 Feature allows users to sign in using Google and Facebook
  .env.example
  .gitignore
  package-lock.json
  package.json
  server/config/passport.js
  server/controllers/authController.js
  server/controllers/userController.js
  server/helpers/authHelper.js
  server/helpers/userHelper.js
  server/index.js
  server/middleware/user.js
  server/routes/authRoutes.js
  server/sequelize/migrations/20200325105904-create-user.js
  server/sequelize/models/user.js
  server/sequelize/seeders/20200325133338-User.js
  server/tests/auth-signin.test.js
  server/tests/mochData/socialMock.js
  server/tests/oauth.test.js
  server/tests/user.test.js
  swagger.json
Labels: TTL Review

#29 171648183-respond-trip: respond to trip request
  .gitignore
  package-lock.json
  server/controllers/tripController.js
  server/helpers/tripHelper.js
  server/middleware/user.js
  server/middleware/validations.js
  server/routes/tripRoutes.js
  server/sequelize/seeders/20200411064133-Trip.js
  server/tests/trip.test.js
  swagger.json
Labels: Peer Review, TTL Review
